import type { Metadata } from "next";
import styles from './page.module.scss'
import './globalThemes.css'
import { Header } from './components/header/header'
import { Footer } from "./components/footer/footer";

export const metadata: Metadata = {
  title: "Webshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.fontOnly}>        {/* Ik' rør ved den her eller tilføj mere styling. Det er kun til font og MÅSKE andet global styling vi mangler */}
        <div className={styles.container}>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
