import type { Metadata } from "next";
import styles from './page.module.scss'
import './globalThemes.css'
import { Header } from './components/header/header'

export const metadata: Metadata = {
  title: "Webshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
        <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
